name: Build npm release

trigger:
  - master

stages:
  - stage: Build_platforms
    jobs:
      - template: ./.ci/build-platform.yml
        parameters:
          platform: Linux
          vmImage: ubuntu-16.04
          esyProject: esy
          STAGING_DIRECTORY: /home/vsts/STAGING
          STAGING_DIRECTORY_UNIX: /home/vsts/STAGING
          ESY__CACHE_INSTALL_PATH: /home/vsts/.esy/3_____________________________________________________________________/i
          ESY__CACHE_SOURCE_TARBALL_PATH: /home/vsts/.esy/source/i

      - template: ./.ci/build-platform.yml
        parameters:
          platform: macOS
          vmImage: macOS-latest
          esyProject: esy
          STAGING_DIRECTORY: /Users/vsts/STAGING
          STAGING_DIRECTORY_UNIX: /Users/vsts/STAGING
          ESY__CACHE_INSTALL_PATH: /Users/vsts/.esy/3____________________________________________________________________/i
          ESY__CACHE_SOURCE_TARBALL_PATH: /Users/vsts/.esy/source/i

      - template: ./.ci/build-windows.yml
        parameters:
          platform: Windows
          vmImage: vs2017-win2016
          esyProject: windows
          STAGING_DIRECTORY: C:\Users\VssAdministrator\STAGING
          STAGING_DIRECTORY_UNIX: /C/Users/VssAdministrator/STAGING
          ESY__CACHE_INSTALL_PATH: /C/Users/VssAdministrator/.esy/3_/i
          ESY__CACHE_SOURCE_TARBALL_PATH: /C/Users/VssAdministrator/.esy/source/i

  - stage: Build_docker
    dependsOn: []
    jobs:
      - job: Docker
        variables:
          dockerId: ulrikaugustsson
          imageName: reason-oidc-provider
        pool:
          vmImage: ubuntu-16.04

        steps:
          - script: docker build -t $(dockerId)/$(imageName):$(Build.BuildId) .
            displayName: "Build docker image"

          - script: docker login -u $(dockerId) -p $(dockerPassword)
            displayName: "Login to docker"

          - script: docker push $(dockerId)/$(imageName)
            displayName: "Push to dockerhub"

  - stage: Deploy_docker
    dependsOn: [Build_docker]
    jobs:
      - deployment: DeployProvider
        pool:
          vmImage: 'Ubuntu-16.04'
        
        environment: oidc-provider-dev
        strategy:
          runOnce:
            deploy:
              steps:
              - task: AzureRmWebAppDeployment@4
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'MPN private dev'
                  appType: 'webAppContainer'
                  WebAppName: 'reason-oidc-provider'
                  DockerNamespace: 'ulrikaugustsson'
                  DockerRepository: 'reason-oidc-provider'
                  DockerImageTag: '$(Build.BuildId)'

  - stage: Integration_tests
    dependsOn: [Deploy_docker]
    jobs:
      - job: Cypress
        pool:
          vmImage: vs2017-win2016

        steps:
          - template: ./.ci/cypress.yml

