parameters:
  platform: "Windows"
  vmImage: "vs2017-win2016"
  STAGING_DIRECTORY: C:\Users\VssAdministrator\STAGING
  STAGING_DIRECTORY_UNIX: /C/Users/VssAdministrator/STAGING
  ESY__CACHE_INSTALL_PATH: /C/Users/VssAdministrator/.esy/3_/i
  ESY__CACHE_SOURCE_TARBALL_PATH: /C/Users/VssAdministrator/.esy/source/i

jobs:
  - job: ${{ parameters.platform }}
    pool:
      vmImage: ${{ parameters.vmImage }}
      demands: node.js
    timeoutInMinutes: 120 # This is mostly for Windows
    continueOnError: True
    variables:
      STAGING_DIRECTORY: ${{ parameters.STAGING_DIRECTORY }}
      STAGING_DIRECTORY_UNIX: ${{ parameters.STAGING_DIRECTORY_UNIX }}
      ESY__CACHE_INSTALL_PATH: ${{ parameters.ESY__CACHE_INSTALL_PATH }}
      ESY__CACHE_SOURCE_TARBALL_PATH: ${{ parameters.ESY__CACHE_SOURCE_TARBALL_PATH }}

    steps:
      - template: ./utils/use-node.yml
      - template: ./utils/use-esy.yml
      - template: ./utils/restore-build-cache.yml
      - script: "esy install --project windows"
        displayName: "esy install"
      - script: "esy build --project windows"
        displayName: "esy build"
      - script: "esy b --project windows dune runtest --profile=windows"
        displayName: "Test command"
      - template: ./utils/publish-build-cache.yml
          