parameters:
  platform: "macOS"
  vmImage: "macOS-latest"
  ESY__CACHE_INSTALL_PATH: $(Pipeline.Workspace)/.esy/3____________________________________________________________________/i

jobs:
  - job: ${{ parameters.platform }}
    pool:
      vmImage: ${{ parameters.vmImage }}
      demands: node.js
    timeoutInMinutes: 120 # This is mostly for Windows
    continueOnError: True

    steps:
      - template: ./utils/use-node.yml
      - template: ./utils/use-esy.yml
      - task: CacheBeta@0
        inputs:
          key: |
            esy
            $(Agent.OS)
            $(Build.SourcesDirectory)/esy.lock/index.json
          path: ${{ parameters.ESY__CACHE_INSTALL_PATH }}
      - script: "esy install"
        displayName: "esy install"
      - script: "esy build"
        displayName: "esy build"
      - script: "esy test"
        displayName: "Test command"
          