parameters:
  platform: "Windows"
  vmImage: "vs2017-win2016"
  ESY__PREFIX_PATH: $(Pipeline.Workspace)/.esy
  ESY__CACHE_INSTALL_PATH: $(Pipeline.Workspace)/.esy/3_/i

jobs:
  - job: ${{ parameters.platform }}
    pool:
      vmImage: ${{ parameters.vmImage }}
      demands: node.js
    timeoutInMinutes: 120 # This is mostly for Windows
    continueOnError: True
    variables:
      ESY__PREFIX: ${{ parameters.ESY__PREFIX_PATH }}

    steps:
      - template: ./utils/use-esy.yml
      - task: CacheBeta@0
        inputs:
          key: |
            esy
            $(Agent.OS)
            ${{ parameters.ESY__CACHE_INSTALL_PATH }}
            $(Build.SourcesDirectory)/esy.lock/index.json
          path: ${{ parameters.ESY__CACHE_INSTALL_PATH }}
      - script: "esy install --project windows"
        displayName: "esy install"
      - script: "esy build --project windows"
        displayName: "esy build"
      - script: "esy b --project windows dune runtest --profile=windows"
        displayName: "Test command"
          